// example/react-todo-app/src/App.jsx
/*
 * @Author: Copyright(c) 2020 Suwings
 * @Date: 2021-04-07 16:34:51
 * @LastEditTime: 2021-04-07 16:57:12
 * @Description: 
 */
// import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <h4>TO DO 列表</h4>
    </div>
  );
}

export default App;

// example/vuetify_example/src/App.vue
<!--
 * @Author: Copyright(c) 2020 Suwings
 * @Date: 2020-12-04 16:25:47
 * @LastEditTime: 2020-12-04 17:22:41
 * @Description: 
-->
<template>
  <v-app>
    <!-- <Header />  -->
    <Menu />
    <v-main>
      <v-container style="margin-left: 255px"> AA </v-container>
    </v-main>
  </v-app>
</template>

<script>
// import Header from "./components/Header";
import Menu from "./components/Menu";

export default {
  name: "App",

  components: {
    // Header,
    Menu,
  },

  data: () => ({
    //
  }),
};
</script>
